[package]
org = "bmapo"
name = "dsa_assignment11"
version = "0.1.0"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = 'C:\Users\bmapo\Downloads\mysql-connector-j-8.0.32.jar'

groupId = "mysql"
artifactId = "mysql-connector-j"
version = "8.0.32"


